export const UI_STRINGS = {
  en: {
    workWithUs: 'Work with us →',
    caseStudy: 'Case Study',
    viewDashboard: 'View Dashboard',
    viewStudy: 'View the Study →',
    viewLinkedin: 'View LinkedIn →',
    downloadCvLabel: 'Download CV',
    cvEnLabel: 'English',
    cvEsLabel: 'Español',
    aboutTag: 'About',
    sectionServices: 'Services',
    sectionSolutions: 'Solutions & Research',
    waPrefill: "Hi Alexander, I found your site and I'd like to discuss a data project.",
    whatsappNote: 'Or just message on WhatsApp — same response time.',
    formNameLabel: 'Your name',
    formCompanyLabel: 'Company',
    formChallengeLabel: 'Data challenge',
    formChallengePlaceholder: 'We have data scattered across 3 systems and no unified view...',
    formWaMsg: (name, company, challenge) =>
      `Hi Alexander, I found your site.\n\nName: ${name}\nCompany: ${company || '—'}\n\nChallenge: ${challenge}`,
    langToggleLabel: 'ES',
    footer: '© 2026 Data Visionary — Data Consulting',
    nav: { services: 'Services', solutions: 'Solutions', impact: 'Impact', approach: 'Approach', about: 'About', contact: 'Contact', training: 'Training Lab' },
  },
  es: {
    workWithUs: 'Trabajemos juntos →',
    caseStudy: 'Caso de Estudio',
    viewDashboard: 'Ver Dashboard',
    viewStudy: 'Ver el Estudio →',
    viewLinkedin: 'Ver LinkedIn →',
    downloadCvLabel: 'Descargar CV',
    cvEnLabel: 'English',
    cvEsLabel: 'Español',
    aboutTag: 'Sobre mí',
    sectionServices: 'Servicios',
    sectionSolutions: 'Soluciones e Investigación',
    waPrefill: 'Hola Alexander, encontré tu web y me gustaría conversar sobre un proyecto de datos.',
    whatsappNote: 'O simplemente escríbeme por WhatsApp — mismo tiempo de respuesta.',
    formNameLabel: 'Tu nombre',
    formCompanyLabel: 'Empresa',
    formChallengeLabel: 'Desafío de datos',
    formChallengePlaceholder: 'Tenemos datos dispersos en 3 sistemas y ninguna vista unificada...',
    formWaMsg: (name, company, challenge) =>
      `Hola Alexander, encontré tu web.\n\nNombre: ${name}\nEmpresa: ${company || '—'}\n\nDesafío: ${challenge}`,
    langToggleLabel: 'EN',
    footer: '© 2026 Data Visionary — Consultoría de Datos',
    nav: { services: 'Servicios', solutions: 'Soluciones', impact: 'Impacto', approach: 'Enfoque', about: 'Sobre mí', contact: 'Contacto', training: 'Training Lab' },
  },
};
